// <auto-generated />
using AssignmentsAtanga.Areas.Olympic.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AssignmentsAtanga.Migrations.Country
{
    [DbContext(typeof(CountryContext))]
    partial class CountryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AssignmentsAtanga.Areas.Olympic.Models.Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = "indoor",
                            Name = "Indoor"
                        },
                        new
                        {
                            CategoryId = "outdoor",
                            Name = "Outdoor"
                        });
                });

            modelBuilder.Entity("AssignmentsAtanga.Areas.Olympic.Models.Country", b =>
                {
                    b.Property<string>("CountryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("photopath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("GameId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = "can",
                            CategoryId = "indoor",
                            GameId = "Winter",
                            Name = "Canada",
                            photopath = "CAN.png"
                        },
                        new
                        {
                            CountryId = "Swe",
                            CategoryId = "indoor",
                            GameId = "Winter",
                            Name = "Sweden",
                            photopath = "SWE.png"
                        },
                        new
                        {
                            CountryId = "gb",
                            CategoryId = "indoor",
                            GameId = "Winter",
                            Name = "Great Britain",
                            photopath = "GB.png"
                        },
                        new
                        {
                            CountryId = "jam",
                            CategoryId = "outdoor",
                            GameId = "Winter",
                            Name = "Jamaica",
                            photopath = "JAM.png"
                        },
                        new
                        {
                            CountryId = "ita",
                            CategoryId = "outdoor",
                            GameId = "Winter",
                            Name = "Italy",
                            photopath = "ITA.png"
                        },
                        new
                        {
                            CountryId = "jap",
                            CategoryId = "outdoor",
                            GameId = "Winter",
                            Name = "Japan",
                            photopath = "JAP.png"
                        },
                        new
                        {
                            CountryId = "ger",
                            CategoryId = "indoor",
                            GameId = "Summer ",
                            Name = "Germany",
                            photopath = "GER.png"
                        },
                        new
                        {
                            CountryId = "Chi",
                            CategoryId = "indoor",
                            GameId = "Summer ",
                            Name = "China",
                            photopath = "CHI.png"
                        },
                        new
                        {
                            CountryId = "mex",
                            CategoryId = "indoor",
                            GameId = "Summer",
                            Name = "Mexico",
                            photopath = "MEX.png"
                        },
                        new
                        {
                            CountryId = "bra",
                            CategoryId = "outdoor",
                            GameId = "Summer",
                            Name = "Brazil",
                            photopath = "BRA.png"
                        },
                        new
                        {
                            CountryId = "neth",
                            CategoryId = "outdoor",
                            GameId = "Summer",
                            Name = "Netherlands",
                            photopath = "NETH.png"
                        },
                        new
                        {
                            CountryId = "usa",
                            CategoryId = "outdoor",
                            GameId = "Summer",
                            Name = "USA",
                            photopath = "USA.png"
                        },
                        new
                        {
                            CountryId = "thai",
                            CategoryId = "indoor",
                            GameId = "Para",
                            Name = "Thailand",
                            photopath = "THAI.png"
                        },
                        new
                        {
                            CountryId = "uru",
                            CategoryId = "indoor",
                            GameId = "Para",
                            Name = "Uruguay",
                            photopath = "URU.png"
                        },
                        new
                        {
                            CountryId = "ukr",
                            CategoryId = "indoor",
                            GameId = "Para",
                            Name = "Ukraine",
                            photopath = "UKR.png"
                        },
                        new
                        {
                            CountryId = "aus",
                            CategoryId = "outdoor",
                            GameId = "Para",
                            Name = "Austria",
                            photopath = "AUS.png"
                        },
                        new
                        {
                            CountryId = "pak",
                            CategoryId = "outdoor",
                            GameId = "Para",
                            Name = "Pakistan",
                            photopath = "PAK.png"
                        },
                        new
                        {
                            CountryId = "zim",
                            CategoryId = "outdoor",
                            GameId = "Para",
                            Name = "Zimbabwe",
                            photopath = "ZIM.png"
                        },
                        new
                        {
                            CountryId = "fra",
                            CategoryId = "indoor",
                            GameId = "Youth",
                            Name = "France",
                            photopath = "FRA.png"
                        },
                        new
                        {
                            CountryId = "cyp",
                            CategoryId = "indoor",
                            GameId = "Youth",
                            Name = "Cyprus",
                            photopath = "CYP.png"
                        },
                        new
                        {
                            CountryId = "rus",
                            CategoryId = "indoor",
                            GameId = "Youth",
                            Name = "Russia",
                            photopath = "RUS.png"
                        },
                        new
                        {
                            CountryId = "fin",
                            CategoryId = "outdoor",
                            GameId = "Youth",
                            Name = "Finland",
                            photopath = "FIN.png"
                        },
                        new
                        {
                            CountryId = "slov",
                            CategoryId = "outdoor",
                            GameId = "Youth",
                            Name = "Slovakia",
                            photopath = "SLOV.png"
                        },
                        new
                        {
                            CountryId = "port",
                            CategoryId = "outdoor",
                            GameId = "Youth",
                            Name = "Portugal",
                            photopath = "PORT.png"
                        });
                });

            modelBuilder.Entity("AssignmentsAtanga.Areas.Olympic.Models.Game", b =>
                {
                    b.Property<string>("GameId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameId = "winter",
                            Name = "Winter Olympics"
                        },
                        new
                        {
                            GameId = "Summer",
                            Name = "Summer Olympics"
                        },
                        new
                        {
                            GameId = "Para",
                            Name = "Paralympics"
                        },
                        new
                        {
                            GameId = "Youth",
                            Name = "Youth Olympic Games"
                        });
                });

            modelBuilder.Entity("AssignmentsAtanga.Areas.Olympic.Models.Country", b =>
                {
                    b.HasOne("AssignmentsAtanga.Areas.Olympic.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssignmentsAtanga.Areas.Olympic.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
